FROM node:21-alpine
WORKDIR /app

ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_KEY
ARG CLOUDINARY_SECRET
ARG MAPBOX_TOKEN
ARG DB_URL
ARG SECRET

ENV CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
ENV CLOUDINARY_KEY=${CLOUDINARY_KEY}
ENV CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
ENV MAPBOX_TOKEN=${MAPBOX_TOKEN}
ENV DB_URL=${DB_URL}
ENV SECRET=${SECRET}

COPY package.json package-lock.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "start"]
